<?php

if( function_exists('acf_add_local_field_group') ) :

// Accordions Block
acf_add_local_field_group(array(
	'key' => 'group_6421a792dbe22',
	'title' => 'Accordions Block',
	'fields' => array(
		array(
			'key' => 'field_6421a79348324',
			'label' => 'Accordions',
			'name' => 'accordions',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'acfe_repeater_stylised_button' => 1,
			'layout' => 'row',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add Accordion',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6421a7f048325',
					'label' => 'Title',
					'name' => 'clickable_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'The title of the accordion, which is always visible.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6421a79348324',
				),
				array(
					'key' => 'field_6421a80448326',
					'label' => 'Content',
					'name' => 'hidden_content',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => 'The main content of the accordion, which is hidden until the title is clicked.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
					'parent_repeater' => 'field_6421a79348324',
				),
				array(
					'key' => 'field_644181333f694',
					'label' => 'Nested?',
					'name' => 'add_a_nested_accordion',
					'aria-label' => '',
					'type' => 'true_false',
					'instructions' => 'You may place as many accordions as you like inside of another accordion and then once more inside one of those accordions (three levels deep).',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'message' => 'Add a nested accordion?',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
					'parent_repeater' => 'field_6421a79348324',
				),
				array(
					'key' => 'field_644180773f692',
					'label' => 'Nested Accordion',
					'name' => 'nested_accordion',
					'aria-label' => '',
					'type' => 'repeater',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array(
						array(
							array(
								'field' => 'field_644181333f694',
								'operator' => '==',
								'value' => '1',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'acfe_save_meta' => 0,
					'acfe_repeater_stylised_button' => 0,
					'layout' => 'row',
					'pagination' => 0,
					'min' => 0,
					'max' => 2,
					'collapsed' => '',
					'button_label' => 'Add Row',
					'rows_per_page' => 20,
					'sub_fields' => array(
						array(
							'key' => 'field_644180cd3f693',
							'label' => 'Title',
							'name' => 'clickable_title',
							'aria-label' => '',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'default_value' => '',
							'maxlength' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'parent_repeater' => 'field_644180773f692',
						),
						array(
							'key' => 'field_6441832d3f695',
							'label' => 'Content',
							'name' => 'hidden_content',
							'aria-label' => '',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
							'parent_repeater' => 'field_644180773f692',
						),
						array(
							'key' => 'field_64419402dc5c6',
							'label' => 'Nested?',
							'name' => 'add_a_nested_accordion_again',
							'aria-label' => '',
							'type' => 'true_false',
							'instructions' => 'You may place as many accordions as you like inside of another accordion and then once more inside one of those accordions (three levels deep).',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_644181333f694',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'message' => 'Add a nested accordion?',
							'default_value' => 0,
							'ui' => 0,
							'ui_on_text' => '',
							'ui_off_text' => '',
							'parent_repeater' => 'field_644180773f692',
						),
						array(
							'key' => 'field_644194efdc5c7',
							'label' => 'Nested Accordion',
							'name' => 'nested_accordion_again',
							'aria-label' => '',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => array(
								array(
									array(
										'field' => 'field_64419402dc5c6',
										'operator' => '==',
										'value' => '1',
									),
								),
							),
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'acfe_save_meta' => 0,
							'acfe_repeater_stylised_button' => 0,
							'layout' => 'row',
							'min' => 0,
							'max' => 0,
							'collapsed' => '',
							'button_label' => 'Add Row',
							'rows_per_page' => 20,
							'sub_fields' => array(
								array(
									'key' => 'field_644196c1d9f8b',
									'label' => 'Title',
									'name' => 'clickable_title',
									'aria-label' => '',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_save_meta' => 0,
									'default_value' => '',
									'maxlength' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'parent_repeater' => 'field_644194efdc5c7',
								),
								array(
									'key' => 'field_6441972ad9f8c',
									'label' => 'Content',
									'name' => 'hidden_content',
									'aria-label' => '',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'acfe_save_meta' => 0,
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
									'parent_repeater' => 'field_644194efdc5c7',
								),
							),
							'parent_repeater' => 'field_644180773f692',
						),
					),
					'parent_repeater' => 'field_6421a79348324',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'cwd/accordions',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'seamless',
	'label_placement' => 'left',
	'instruction_placement' => 'above_field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
));

// Card Grid Block
acf_add_local_field_group(array(
	'key' => 'group_63e2befd84461',
	'title' => 'Card Grid Block',
	'fields' => array(
		array(
			'key' => 'field_641b1f86b08bd',
			'label' => 'Title',
			'name' => 'cards_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'The title that appears above the cards.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_641b2036b08be',
			'label' => 'Title Color',
			'name' => 'cards_title_color',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => 'The text color for the title.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'black' => 'Black',
				'red' => 'Red',
			),
			'default_value' => 'black',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_63e2befdfbf8a',
			'label' => 'Cards',
			'name' => 'cards',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 1,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 3,
			'max' => 9,
			'collapsed' => '',
			'button_label' => 'Add Card',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_63e2bf10fbf8b',
					'label' => 'Title',
					'name' => 'card_title',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'The title of the card.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_63e2befdfbf8a',
				),
				array(
					'key' => 'field_63e2bf17fbf8c',
					'label' => 'Body',
					'name' => 'card_body',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => 'If linking the entire card, do not insert any links into the body text.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'visual',
					'toolbar' => 'basic',
					'media_upload' => 1,
					'delay' => 0,
					'parent_repeater' => 'field_63e2befdfbf8a',
				),
				array(
					'key' => 'field_63e41cf92f8da',
					'label' => 'Link',
					'name' => 'card_link',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => 'Optional; if included, the entire card will link to this url. The link text will not be used in the display and can be left blank.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'parent_repeater' => 'field_63e2befdfbf8a',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'cwd/cards',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'above_field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
));

// Events Block
acf_add_local_field_group(array(
	'key' => 'group_6407826360995',
	'title' => 'Events Block',
	'fields' => array(
		array(
			'key' => 'field_640782635a3dd',
			'label' => 'Heading',
			'name' => 'events_heading',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'The heading text for the section. Recommended options are "Important Dates" or "Events."',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'Important Dates',
			'maxlength' => 60,
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_64404f0b99ca4',
			'label' => 'Events Archive Link',
			'name' => 'events_view_all_link',
			'aria-label' => '',
			'type' => 'link',
			'instructions' => 'The link to view additional related events; displays in the upper right corner of the block.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'return_format' => 'array',
		),
		array(
			'key' => 'field_640785185a3df',
			'label' => 'Number of Events',
			'name' => 'events_number',
			'aria-label' => '',
			'type' => 'number',
			'instructions' => 'The number of events to display. Recommended to limit to 3 or 4 events in order to display in a single line; however events will display in a grid if a larger number is specified (12 max).',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 4,
			'min' => 3,
			'max' => 12,
			'placeholder' => '',
			'step' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_640785b85a3e0',
			'label' => 'Filter',
			'name' => 'events_filter',
			'aria-label' => '',
			'type' => 'acfe_taxonomy_terms',
			'instructions' => 'Optionally select taxonomy terms by which to filter the event listings.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => '',
			'allow_terms' => '',
			'allow_level' => '',
			'field_type' => 'select',
			'default_value' => array(
			),
			'return_format' => 'object',
			'ui' => 1,
			'allow_null' => 0,
			'placeholder' => 'All events',
			'multiple' => 1,
			'ajax' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'choices' => array(
			),
			'search_placeholder' => '',
			'layout' => '',
			'toggle' => 0,
			'allow_custom' => 0,
			'other_choice' => 0,
		),
		array(
			'key' => 'field_64079face4628',
			'label' => 'Background Color',
			'name' => 'events_bg',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => 'The background color for this section.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'gray' => 'Light Gray',
				'white' => 'White',
			),
			'default_value' => 'gray',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'cwd/events',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'above_field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
));

// Flexible Cards Block
acf_add_local_field_group(array(
	'key' => 'group_641a11c22eff4',
	'title' => 'Flexible Cards Block',
	'fields' => array(
		array(
			'key' => 'field_641a1375c62dd',
			'label' => 'Layout',
			'name' => 'flex_cards_layout',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => 'Should the cards be full-width, or in a grid of two or three across?',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'full-width' => 'Stack',
				'flex-6' => 'Grid of Two',
				'flex-4' => 'Grid of Three',
			),
			'default_value' => 'stack',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_641a1254cccca',
			'label' => 'Card Backgrounds',
			'name' => 'flex_cards_bg',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => 'Use gray cards in white sections (default); use white cards in gray sections.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'bg-gray' => 'Gray',
				'bg-white' => 'White',
			),
			'default_value' => 'gray',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_641b290803cd0',
			'label' => 'Please Note:',
			'name' => '',
			'aria-label' => '',
			'type' => 'message',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => 'Full-width cards will look best with both images and text.<br><br>For grid layouts, try to keep elements and content length consistent across all cards in the grid (e.g. all cards should contain both images and text, instead of some having both and some having only one).',
			'new_lines' => 'wpautop',
			'esc_html' => 0,
		),
		array(
			'key' => 'field_641a11c2cccc7',
			'label' => 'Cards',
			'name' => 'flex_cards',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 1,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 1,
			'max' => 0,
			'collapsed' => 'field_641a11ddcccc8',
			'button_label' => 'Add Card',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_641a11ddcccc8',
					'label' => 'Image',
					'name' => 'flex_card_image',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => '',
					'return_format' => 'array',
					'acfe_thumbnail' => 0,
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'library' => 'all',
					'parent_repeater' => 'field_641a11c2cccc7',
				),
				array(
					'key' => 'field_641a1202cccc9',
					'label' => 'Text',
					'name' => 'flex_card_text',
					'aria-label' => '',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 0,
					'delay' => 0,
					'parent_repeater' => 'field_641a11c2cccc7',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'cwd/flex-cards',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'above_field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
));

// News Block
acf_add_local_field_group(array(
	'key' => 'group_63e67f748bb84',
	'title' => 'News Block',
	'fields' => array(
		array(
			'key' => 'field_64404d544edd3',
			'label' => 'News Archive Link',
			'name' => 'news_view_all_link',
			'aria-label' => '',
			'type' => 'link',
			'instructions' => 'The link to view additional related news items; displays in the upper right corner of the block.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_save_meta' => 0,
			'return_format' => 'array',
		),
		array(
			'key' => 'field_63e67f7446348',
			'label' => 'Filter',
			'name' => 'news_filter',
			'aria-label' => '',
			'type' => 'acfe_taxonomy_terms',
			'instructions' => 'Optionally select taxonomy terms by which to filter the news listings.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'taxonomy' => '',
			'allow_terms' => '',
			'allow_level' => '',
			'field_type' => 'select',
			'default_value' => array(
			),
			'return_format' => 'object',
			'ui' => 1,
			'allow_null' => 0,
			'placeholder' => 'All news',
			'multiple' => 1,
			'ajax' => 0,
			'save_terms' => 0,
			'load_terms' => 0,
			'choices' => array(
			),
			'search_placeholder' => '',
			'layout' => '',
			'toggle' => 0,
			'allow_custom' => 0,
			'other_choice' => 0,
		),
		array(
			'key' => 'field_63e6a911e731c',
			'label' => 'Fallback Listing Image',
			'name' => 'news_fallback_img',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'Optional. Add an image to override the default fallback image, used on listings that don\'t have a featured image of their own.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'acfe_thumbnail' => 0,
			'return_format' => 'id',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
			'library' => 'all',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'cwd/news',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'above_field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
));

// Quote Block
acf_add_local_field_group(array(
	'key' => 'group_63e29406bfce0',
	'title' => 'Quote Block',
	'fields' => array(
		array(
			'key' => 'field_63e29408397c0',
			'label' => 'Quote Text',
			'name' => 'quote_text',
			'aria-label' => '',
			'type' => 'textarea',
			'instructions' => 'The main text of the quote. Recommended to limit to a sentence or two, around 300 characters or less.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'acfe_textarea_code' => 0,
			'maxlength' => 500,
			'rows' => '',
			'placeholder' => '',
			'new_lines' => '',
		),
		array(
			'key' => 'field_63e29422397c1',
			'label' => 'Attribution',
			'name' => 'quote_attribution',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'Optionally include an attribution for the quote. If included, it will be displayed after the main quote text with a hyphen prepended.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '–',
			'append' => '',
		),
		array(
			'key' => 'field_63e29501397c2',
			'label' => 'Image',
			'name' => 'quote_image',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => 'If included, the image will display offset to the left of the quote text.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'uploader' => '',
			'acfe_thumbnail' => 0,
			'return_format' => 'array',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
			'library' => 'all',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'cwd/quote',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'above_field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
));

// Section Block
acf_add_local_field_group(array(
	'key' => 'group_63cf134934b58',
	'title' => 'Full-Width Section Block',
	'fields' => array(
		array(
			'key' => 'field_63cf13498a1d0',
			'label' => 'Background Color',
			'name' => 'section_bg',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'white' => 'White',
				'gray' => 'Light Gray',
			),
			'default_value' => 'white',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_63d00c422d1d3',
			'label' => 'Title',
			'name' => 'section_title',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => 'The title of this section.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_63d00c692d1d4',
			'label' => 'Title Visibility',
			'name' => 'section_display_title',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => 'Toggle this off if the title should not be displayed on the frontend of the website (you can mostly ignore this setting).',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 1,
			'ui_on_text' => 'Show',
			'ui_off_text' => 'Hide',
			'ui' => 1,
		),
		array(
			'key' => 'field_63d00d9b75bd4',
			'label' => 'Title Color',
			'name' => 'section_title_color',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_63d00c692d1d4',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'black' => 'Black',
				'red' => 'Red',
			),
			'default_value' => 'black',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'cwd/section',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'above_field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
));

// Tabbed Content Block
acf_add_local_field_group(array(
	'key' => 'group_63d013688d867',
	'title' => 'Tabbed Content Block',
	'fields' => array(
		array(
			'key' => 'field_63d014fae1495',
			'label' => 'Active Tab Color',
			'name' => 'tabbed_content_tab_color',
			'aria-label' => '',
			'type' => 'button_group',
			'instructions' => 'The background color of the active tab.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'black' => 'Black',
				'red' => 'Red',
				'blue' => 'Blue',
			),
			'default_value' => '',
			'return_format' => 'value',
			'allow_null' => 0,
			'layout' => 'horizontal',
		),
		array(
			'key' => 'field_63d01368bb719',
			'label' => 'Tabs',
			'name' => 'tabbed_content_tabs',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'A list of 3-10 tabs. Images are optional, but will look best on mobile if no more than one tab in a row is without an image.',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'acfe_repeater_stylised_button' => 1,
			'layout' => 'block',
			'pagination' => 0,
			'min' => 3,
			'max' => 10,
			'collapsed' => 'field_63d013a6bb71a',
			'button_label' => 'Add Tab',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_63d013a6bb71a',
					'label' => 'Label',
					'name' => 'tab_label',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => 'The label for the tab, which will also appear as a heading in the tab content area on hover.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_63d01368bb719',
				),
				array(
					'key' => 'field_63d013b6bb71b',
					'label' => 'Content',
					'name' => 'tab_content',
					'aria-label' => '',
					'type' => 'textarea',
					'instructions' => 'The main content of the tab, which appears when the tab is hovered over.',
					'required' => 1,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'acfe_textarea_code' => 0,
					'maxlength' => '',
					'rows' => '',
					'placeholder' => '',
					'new_lines' => '',
					'parent_repeater' => 'field_63d01368bb719',
				),
				array(
					'key' => 'field_63d0143fbb71c',
					'label' => 'Button',
					'name' => 'tab_button',
					'aria-label' => '',
					'type' => 'link',
					'instructions' => 'A call to action button displayed under the main tab content. Not required, but it is recommended to include a button for every tab.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'parent_repeater' => 'field_63d01368bb719',
				),
				array(
					'key' => 'field_63d018a16d825',
					'label' => 'Background Image',
					'name' => 'tab_bg',
					'aria-label' => '',
					'type' => 'image',
					'instructions' => 'The background image for the tab content area. If no image is included, the tab content will display a dark gray triangle pattern as the background.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'uploader' => '',
					'acfe_thumbnail' => 0,
					'return_format' => 'url',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
					'preview_size' => 'medium',
					'library' => 'all',
					'parent_repeater' => 'field_63d01368bb719',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'cwd/tabs',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'above_field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
));

// WYSIWYG Text Block
acf_add_local_field_group(array(
	'key' => 'group_6419ca3322823',
	'title' => 'WYSIWYG Block',
	'fields' => array(
		array(
			'key' => 'field_6419ca381960f',
			'label' => 'Text',
			'name' => 'wysiwyg_text',
			'aria-label' => '',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'cwd/wysiwyg',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'above_field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
	'acfe_display_title' => '',
	'acfe_autosync' => '',
	'acfe_form' => 0,
	'acfe_meta' => '',
	'acfe_note' => '',
));

endif;