<?php

// Custom fields for events content type
acf_add_local_field_group(array(
	'key' => 'group_5e87a6189e8c8',
	'title' => 'Events Fields',
	'fields' => array(
		array(
			'key' => 'field_5e8cbe2e0afc4',
			'label' => 'Description',
			'name' => 'description',
			'type' => 'wysiwyg',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'tabs' => 'all',
			'toolbar' => 'full',
			'media_upload' => 1,
			'delay' => 0,
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5e87a7238e664',
			'label' => 'Start Date',
			'name' => 'date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 1,
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5e93bd815aea0',
			'label' => 'Event Start Time',
			'name' => 'start_time',
			'type' => 'time_picker',
			'instructions' => '',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i A',
			'return_format' => 'g:i A',
			'first_day' => 1,
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5e87a7238e665',
			'label' => 'End Date',
			'name' => 'end_date',
			'type' => 'date_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'F j, Y',
			'return_format' => 'F j, Y',
			'first_day' => 1,
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5e93bd815aea1',
			'label' => 'Event End Time',
			'name' => 'end_time',
			'type' => 'time_picker',
			'instructions' => '',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'display_format' => 'g:i A',
			'return_format' => 'g:i A',
			'first_day' => 1,
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5e93bd9e47d34',
			'label' => 'Is All Day Event?',
			'name' => 'is_all_day',
			'type' => 'true_false',
			'instructions' => 'Check this box to let attendees know this is event will run all day.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5e87a822aefbe',
			'label' => 'Location',
			'name' => 'location',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5e87a822aefbf',
			'label' => 'Room',
			'name' => 'room',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5e979f1e9f171',
			'label' => 'Event Url',
			'name' => 'event_url',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5e979f1e9f172',
			'label' => 'Zoom Link',
			'name' => 'zoom_link',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5e979f1e9f174',
			'label' => 'Contact Email',
			'name' => 'email',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5f63ce9c9ad2a',
			'label' => 'Photo image URL',
			'name' => 'photo_url',
			'type' => 'text',
			'instructions' => 'Typically this fields is set by CD Events Feed plugin, but this can be used to set the URL for the featured image if it hosted somewhere else.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5fff109x86ffa',
			'label' => 'Image',
			'name' => 'image_id',
			'type' => 'image',
			'instructions' => 'If the "Featured image URL" field above is empty, you must choose an image here. This will be used as the featured image for the post and as the thumbnail for all listings and teasers.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'show_in_graphql' => 1,
			'uploader' => 'wp',
			'acfe_thumbnail' => 0,
			'return_format' => 'id',
			'preview_size' => 'medium',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5e8fbc15010fd',
			'label' => 'event_id',
			'name' => 'event_id',
			'type' => 'text',
			'instructions' => 'Set by CD Events plugin do not edit.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'hidden',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_5e979f1e9f173',
			'label' => 'Localist Url',
			'name' => 'localist_url',
			'type' => 'text',
			'instructions' => 'Set by CD Events plugin do not edit.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => 'hidden',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'show_in_graphql' => 1,
		),
		array(
			'key' => 'field_600eb590134f9',
			'label' => 'Teaser Text',
			'name' => 'teaser_text',
			'type' => 'textarea',
			'instructions' => 'Use this text field for the home page teaser.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_600eb590134ba',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => '',
			'new_lines' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'events',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'acf_after_title',
	'style' => 'seamless',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'excerpt',
		1 => 'discussion',
		2 => 'comments',
		3 => 'slug',
		4 => 'author',
		5 => 'format',
		6 => 'categories',
		7 => 'tags',
		8 => 'send-trackbacks',
	),
	'active' => true,
	'description' => '',
	'show_in_graphql' => 1,
	'graphql_field_name' => 'event',
));